export const AUTH_CHANGED = 'AUTH_CHANGED';
export const AUTH_SAVE_GITHUB_TOKEN = 'AUTH_SAVE_GITHUB_TOKEN';

export const FIREBASE_CONFIG = 'FIREBASE_CONFIG';

export const NOOP = 'NOOP';

export const UPDATE_PR_LIST = 'UPDATE_PR_LIST';
